# Generated by Django 3.2.16 on 2024-01-24 21:40

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0004_birthday_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='days_left_for_birthday',
            field=computed_property.fields.ComputedTextField(compute_from='calculate', default=0, editable=False),
            preserve_default=False,
        ),
    ]
