# Generated by Django 3.2.16 on 2024-01-26 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0008_auto_20240127_0359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
